feat: подключил безопасность
AlKl1M/fintech-deal pull request #2
Opened 2024-07-29 08:17 UTC by AlKl1M

2024-07-30 10:12 UTC, gobaz095 requested changes
Ну и напрашивается enum для ролей, который тоже может быть в отдельной либе

2024-07-30 10:12 UTC, gobaz095 commented on src/main/java/com/alkl1m/deal/web/controller/DealController.java
> +            @AuthenticationPrincipal UserDetailsImpl userDetails
в сделка уже нужны роли внутри, PreAuthorize не подойдет.
Но мы можем запихнуть все это в securityContextHolder и пользоваться где угодно при помощи Util, либо отдельной либы, типа role-model, чтобы в каждом сервисе не писать util классы. То есть делаем либу, которая проставляет securityContextHolder из нашего токена при помощи OncePerRequestFilter, там же пишем методы, которые будут проверять Authority.

Почитай тут про OncePerRequestFilter, где мы можем в контекст положить все нам нужное:
https://habr.com/ru/articles/784508/
https://www.baeldung.com/spring-onceperrequestfilter
Тут про получение ролей:
https://stackoverflow.com/questions/10092882/how-can-i-get-the-current-user-roles-from-spring-security-3-1

2024-07-30 14:54 UTC, AlKl1M commented on src/main/java/com/alkl1m/deal/service/impl/DealServiceImpl.java
> +        Set<String> userRoles = getUserRoles(userDetails);
https://github.com/AlKl1M/fintech-deal/pull/2/commits/38bf9d8143d8fd8cecbb32c73d5d86099603247a

2024-07-30 14:55 UTC, AlKl1M commented on src/main/java/com/alkl1m/deal/web/controller/DealController.java
> +                                                    @AuthenticationPrincipal UserDetailsImpl userDetails) {
Я исправил это (переместил из конфигурации в PreAuthorize), но UserDetailsImpl тут не для проверки ролей, а для получения userId (это нам нужно для указания данных о пользователе, который обновлял или создавал сделки) https://github.com/AlKl1M/fintech-deal/pull/2/commits/80ada4fc31b3f0ca96c86b90a33ec4ce1a6d2ec0

2024-07-30 14:56 UTC, AlKl1M commented on src/main/java/com/alkl1m/deal/web/controller/DealController.java
> +            @AuthenticationPrincipal UserDetailsImpl userDetails
https://github.com/AlKl1M/fintech-deal/pull/2/commits/80ada4fc31b3f0ca96c86b90a33ec4ce1a6d2ec0 но вообще в JwtFilter такой подход и используется, просто там оно загружается в контекст, а потом в моих контроллерах я достаю нужные мне данные из userDetails, но они отнюдь не для проверки ролей, а просто для вставки их в бд

2024-08-01 17:08 UTC, gobaz095 approved these changes
Сливай

2024-08-01 17:57 UTC, merged